### ISSUE TITLE
Click en tarjeta de finales muestra Toast indebido

### ISSUE THREAD

**Issue by Franverri** [Franverri/TDP-SIU#12]

**Comment by Franverri** [comment]
Se encontró el bug el cual se producía cuando se volvia hacia atras en las pantallas del stack y cuando se llegaba a la activity de "Finales" al no llamarse el método "onCreate" no se asignaba en "false" la posibilidad de clickear las tarjetas.
Para solucionarlo se movió dicha tarea al método "onResume" que si es llamado.
@federicobalina validar la correción del bug

**Comment by federicobalina** [comment]
Se modificó la solución, las activityies FinalesActivity y FinalesOpcionesActivity pasan una variable al constructor de FinalesAdapter referida a si las cards deben poder ser clickeadas o no. Se verificó el correcto funcionamiento
